package com.mycompany.desktopapplication;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yanika
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ViewOption = new javax.swing.JMenu();
        ViewInventoryButton = new javax.swing.JMenuItem();
        ViewClientsButton = new javax.swing.JMenuItem();
        ViewOrders = new javax.swing.JMenuItem();
        AddOption = new javax.swing.JMenu();
        AddInventoryButton = new javax.swing.JMenuItem();
        UpdateOption = new javax.swing.JMenu();
        UpdateInventoryButton = new javax.swing.JMenuItem();
        DeleteOption = new javax.swing.JMenu();
        DeleteInventoryButton = new javax.swing.JMenuItem();
        HelpOption = new javax.swing.JMenu();
        ExitButton = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 3, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 204));
        jLabel1.setText("Rose Clothing");

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\htdocs\\DesktopApplication\\LogoPng.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\htdocs\\DesktopApplication\\text.PNG")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(509, 509, 509))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(260, 260, 260))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ViewOption.setBackground(new java.awt.Color(255, 255, 255));
        ViewOption.setText("View");

        ViewInventoryButton.setText("View Inventory");
        ViewInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInventoryButtonActionPerformed(evt);
            }
        });
        ViewOption.add(ViewInventoryButton);

        ViewClientsButton.setText("View Clients");
        ViewClientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewClientsButtonActionPerformed(evt);
            }
        });
        ViewOption.add(ViewClientsButton);

        ViewOrders.setText("View Orders");
        ViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrdersActionPerformed(evt);
            }
        });
        ViewOption.add(ViewOrders);

        jMenuBar1.add(ViewOption);

        AddOption.setBackground(new java.awt.Color(255, 255, 255));
        AddOption.setText("Add");

        AddInventoryButton.setText("Add Inventory");
        AddInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInventoryButtonActionPerformed(evt);
            }
        });
        AddOption.add(AddInventoryButton);

        jMenuBar1.add(AddOption);

        UpdateOption.setBackground(new java.awt.Color(255, 255, 255));
        UpdateOption.setText("Update");

        UpdateInventoryButton.setText("Update Inventory");
        UpdateInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInventoryButtonActionPerformed(evt);
            }
        });
        UpdateOption.add(UpdateInventoryButton);

        jMenuBar1.add(UpdateOption);

        DeleteOption.setBackground(new java.awt.Color(255, 255, 255));
        DeleteOption.setText("Delete");

        DeleteInventoryButton.setText("Delete Inventory");
        DeleteInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteInventoryButtonActionPerformed(evt);
            }
        });
        DeleteOption.add(DeleteInventoryButton);

        jMenuBar1.add(DeleteOption);

        HelpOption.setBackground(new java.awt.Color(255, 255, 255));
        HelpOption.setText("Help");

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        HelpOption.add(ExitButton);

        jMenuItem3.setText("How To Use");
        HelpOption.add(jMenuItem3);

        jMenuBar1.add(HelpOption);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInventoryButtonActionPerformed
        // TODO add your handling code here:
       ViewInventory vi = new ViewInventory();
        vi.setVisible(true);
    }//GEN-LAST:event_ViewInventoryButtonActionPerformed

    private void ViewClientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewClientsButtonActionPerformed
        // TODO add your handling code here:
        ViewClients vc = new ViewClients();
        vc.setVisible(true);
    }//GEN-LAST:event_ViewClientsButtonActionPerformed

    private void DeleteInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteInventoryButtonActionPerformed
        // TODO add your handling code here:
        DeleteInventory vd = new DeleteInventory();
        vd.setVisible(true);
    }//GEN-LAST:event_DeleteInventoryButtonActionPerformed

    private void UpdateInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInventoryButtonActionPerformed
        // TODO add your handling code here:
        UpdateInventory vu = new UpdateInventory();
        vu.setVisible(true);
    }//GEN-LAST:event_UpdateInventoryButtonActionPerformed

    private void AddInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInventoryButtonActionPerformed
        // TODO add your handling code here:
        AddInventory va = new AddInventory();
        va.setVisible(true);
    }//GEN-LAST:event_AddInventoryButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog( this , "Are You Sure You Want To Exit ??" ,"Warning ",JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION)
        {
            System.exit(0);
            
        }
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOrdersActionPerformed
        // TODO add your handling code here:
             ViewOrders vo = new ViewOrders();
            vo.setVisible(true);
    }//GEN-LAST:event_ViewOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddInventoryButton;
    private javax.swing.JMenu AddOption;
    private javax.swing.JMenuItem DeleteInventoryButton;
    private javax.swing.JMenu DeleteOption;
    private javax.swing.JMenuItem ExitButton;
    private javax.swing.JMenu HelpOption;
    private javax.swing.JMenuItem UpdateInventoryButton;
    private javax.swing.JMenu UpdateOption;
    private javax.swing.JMenuItem ViewClientsButton;
    private javax.swing.JMenuItem ViewInventoryButton;
    private javax.swing.JMenu ViewOption;
    private javax.swing.JMenuItem ViewOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
